online_avoidance_controller:
  ros__parameters:

    control_rate: 50.0

    control_points:
      - fr3_link1
      - fr3_link2
      - fr3_link3
      - fr3_link4
      - fr3_link5
      - fr3_link6
      - fr3_link7
      - fr3_link8

    control_points_offsets_yaml: |
      fr3_link1:
        - [0.0, 0.0, 0.0]

      fr3_link2:
        - [0.0, 0.0, 0.0]
        - [0.05, 0.0, 0.0]
        - [-0.05, 0.0, 0.0]

      fr3_link3:
        - [0.0, 0.0, 0.0]
        - [0.06, 0.0, 0.0]
        - [-0.06, 0.0, 0.0]

      fr3_link4:
        - [0.0, 0.0, 0.0]
        - [0.06, 0.0, 0.0]
        - [-0.06, 0.0, 0.0]

      fr3_link5:
        - [0.0, 0.0, 0.0]
        - [0.06, 0.0, 0.0]
        - [-0.06, 0.0, 0.0]

      fr3_link6:
        - [0.0, 0.0, 0.0]
        - [0.05, 0.0, 0.0]
        - [-0.05, 0.0, 0.0]

      fr3_link7:
        - [0.0, 0.0, 0.0]
        - [0.04, 0.0, 0.0]
        - [-0.04, 0.0, 0.0]

      fr3_link8:
        - [0.0, 0.0, 0.0]
        - [0.03, 0.0, 0.0]
        - [-0.03, 0.0, 0.0]


    influence_distance: 0.30
    safety_margin: 0.08

    repulsive_gain: 0.4

    damping_max: 0.05
    singularity_threshold: 0.05

    max_joint_velocity: 1.0

    planning_scene_topic: "/planning_scene"
    monitor_planning_scene: true

    robot_description_param: "robot_description"
    base_frame: "fr3_link0"
    ee_frame: "fr3_link8"

    verbose_logging: false
