link_mesh_files:
  fr3_link0: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link0.stl
  fr3_link1: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link1.stl
  fr3_link2: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link2.stl
  fr3_link3: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link3.stl
  fr3_link4: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link4.stl
  fr3_link5: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link5.stl
  fr3_link6: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link6.stl
  fr3_link7: /ros2_ws/src/franka_description/meshes/robot_arms/fr3/collision/link7.stl
  fr3_link8: /ros2_ws/src/franka_description/meshes/robot_ee/franka_hand_white/collision/hand.stl