franka_motion_server:
  ros__parameters:
    move_group_name: fr3_arm
    base_link_name: fr3_link0
    end_effector_name: fr3_hand_tcp

    planner_id: RRTstar
    allowed_planning_time: 5.0

    # Reduce MoveIt execution speed to improve reactive avoidance effectiveness
    max_velocity_scaling_factor: 0.05
    max_acceleration_scaling_factor: 0.05

    max_motion_retries: 3
    max_ik_retries: 5
    ik_timeout: 10.0
