velocity_control_blender:
  ros__parameters:
    kp: 3.0
    max_vel: 0.15        # rad/s
    waypoint_threshold: 0.05
    final_threshold: 0.01
    approach_velocity_threshold: 0.03   # oltre questo, alpha va verso 1
    min_alpha_close: 0.3    
