robot:
  joint_names:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7

  segment_links:
    - fr3_link1
    - fr3_link2
    - fr3_link3
    - fr3_link4
    - fr3_link5
    - fr3_link6
    - fr3_link7
    - fr3_link8

topics:
  multi_distance: /human_robot/multi_distance
