"""Write franka_description's self-collision capsules as franka_sim data.

The robot's CBF self-collision rows use the OFFICIAL capsules franka_description
emits with ``with_sc:=true`` (franka_experiments/utils/self_collision.py). This
script runs ONCE, in the ROS container, and stores them in the frame of the
physical link they belong to, so franka_sim can measure the same geometry with
MuJoCo body poses and no ROS at runtime:

    source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash
    PYTHONPATH=/ros2_ws/src:/ros2_ws/src/franka_experiments python3 -m franka_sim.scripts.extract_sc_capsules

It also checks that each URDF link frame coincides with the MuJoCo body of the
same name at random configurations (the transform it relies on).
"""
from __future__ import annotations

import os
import xml.etree.ElementTree as ET

import numpy as np
import yaml

from franka_experiments.utils.kinematics import build_urdf_with_sc
from franka_experiments.utils.self_collision import parse_sc_capsules, rpy_to_matrix

OUT = os.path.join(os.path.dirname(__file__), '..', 'assets', 'franka_fr3', 'self_collision_capsules.yaml')


def main():
    path = build_urdf_with_sc(hand=True, safety_distance=0.0)
    xml = open(path).read()
    root = ET.fromstring(xml)
    # Fixed joint parent → child_sc: the capsule's frame inside its physical link.
    sc_in_parent = {}
    for j in root.findall('joint'):
        child = j.find('child').get('link')
        if child.endswith('_sc'):
            o = j.find('origin')
            xyz = np.array([float(v) for v in (o.get('xyz') or '0 0 0').split()]) if o is not None else np.zeros(3)
            rpy = np.array([float(v) for v in (o.get('rpy') or '0 0 0').split()]) if o is not None else np.zeros(3)
            sc_in_parent[child] = (j.find('parent').get('link'), rpy_to_matrix(*rpy), xyz)
    caps = []
    for c in parse_sc_capsules(xml):
        parent, R, t = sc_in_parent[c.frame]
        caps.append(dict(body=parent, p1=[round(float(v), 6) for v in R @ c.p1 + t],
                         p2=[round(float(v), 6) for v in R @ c.p2 + t], radius=round(float(c.radius), 6)))
    check_frames(path, sorted({c['body'] for c in caps}))
    with open(OUT, 'w') as f:
        f.write('# franka_description self-collision capsules (with_sc:=true, safety_distance 0),\n'
                '# endpoints in the frame of the physical link. Generated by\n'
                '# franka_sim/scripts/extract_sc_capsules.py; do not edit by hand.\n')
        yaml.safe_dump({'capsules': caps}, f, sort_keys=False)
    print(len(caps), 'capsules ->', os.path.abspath(OUT))
    os.unlink(path)


def check_frames(urdf_path, bodies):
    """URDF link frame == MuJoCo body frame of the same name, at random q."""
    import mujoco
    import pinocchio as pin
    m = mujoco.MjModel.from_xml_path(os.path.join(os.path.dirname(__file__), '..', 'assets', 'franka_fr3', 'scene_cbf.xml'))
    d = mujoco.MjData(m)
    model = pin.buildModelFromUrdf(urdf_path); data = model.createData()
    jq = [model.idx_qs[model.getJointId(f'fr3_joint{i}')] for i in range(1, 8)]
    mq = [m.jnt_qposadr[mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_JOINT, f'fr3_joint{i}')] for i in range(1, 8)]
    rng = np.random.default_rng(0)
    worst = 0.0
    for _ in range(20):
        q7 = rng.uniform(-1.5, 1.5, 7); q7[3] = rng.uniform(-2.8, -0.3); q7[5] = rng.uniform(0.6, 3.5)
        q = pin.neutral(model); q[jq] = q7
        pin.forwardKinematics(model, data, q); pin.updateFramePlacements(model, data)
        d.qpos[:] = 0; d.qpos[mq] = q7; mujoco.mj_kinematics(m, d)
        for b in bodies:
            T = data.oMf[model.getFrameId(b)]
            bid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, b)
            worst = max(worst, float(np.linalg.norm(T.translation - d.xpos[bid])),
                        float(np.abs(T.rotation - d.xmat[bid].reshape(3, 3)).max()))
    print(f'URDF vs MuJoCo link frames, worst mismatch over 20 poses: {worst:.2e}')
    if worst > 1e-4:
        raise SystemExit('frames differ: the capsules cannot be placed with MuJoCo body poses')


if __name__ == '__main__':
    main()
